### ISSUE TITLE
Digital Downloadable Products

### ISSUE THREAD

**Issue by chrisformula** [jsdecena/laracom#227]
Is it possible to create downloadable product and how?

**Comment by Messhias** [comment]
What do you mean by "downloadable product"? CSV of the products listing?

**Comment by jsdecena** [comment]
> What do you mean by "downloadable product"? CSV of the products listing?

I think he meant PDFs, html themes etc.

**Comment by Messhias** [comment]
> > What do you mean by "downloadable product"? CSV of the products listing?
> 
> I think he meant PDFs (e-books), HTML themes etc.

if he meant that this needs to be separated into parts because otherwise will be a huge load of developments if someone starts to develop could be at first place PDF's, CSV and something useful for the end-user. 

HTML and other kinds of files, I don't see how this is could be useful for end-users, it's a nice to have feature but I don't see it as a necessary feature.
